#pragma once
namespace OL
{
class AExpr;
class ASimpleExpr;
class AConstExpr;
class AConstructor;
class AFuncExpr;
class ATypeCast;
class ASuffixedExpr;
class ADereferance;
class ADotMember;
class ABracketMember;
class ACall;
class ANormalCall;
class AColonCall;
class ASubexpr;
class APrimaryExpr;
class AVarRef;
class AParentheses;
class ATypeCast;
class ASelf;
class ASuper;
class ATypeIdentity;
class AIntrinsicType;
class ANamedType;
class AFuncType;
class AArrayType;
class AMapType;
class AVariableParamRef;
}